version: "3"

services:
  bot:
    build: .
    container_name: telegram_bot
    restart: always
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27118:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}

